;A configuration File

[XComGame.X2ItemTemplateManager]

+Loadouts=(LoadoutName="AdvShieldBearerM2_Loadout_BL", Items[0]=(Item="AdvShieldBearerM2_WPN"), Items[1]=(Item="StasisVest"))

+Loadouts=(LoadoutName="AdvShieldBearerM3_Loadout_BL", Items[0]=(Item="AdvShieldBearerM3_WPN"), Items[1]=(Item="StasisVest"))

+Loadouts=(LoadoutName="AdvTrooperM1_Loadout_BL", Items[0]=(Item="AdvTrooperM1_WPN"), Items[1]=(Item="NanofiberVest"))

+Loadouts=(LoadoutName="AdvTrooperM2_Loadout_BL", Items[0]=(Item="AdvTrooperM2_WPN"), Items[1]=(Item="AdventTrooperMk2Grenade"), Items[2]=(Item="NanofiberVest"))

+Loadouts=(LoadoutName="AdvTrooperM3_Loadout_BL", Items[0]=(Item="AdvTrooperM3_WPN"), Items[1]=(Item="AdventTrooperMk3Grenade"), Items[2]=(Item="NanofiberVest"))

+Loadouts=(LoadoutName="AdvPriestM1_Loadout_BL", Items[0]=(Item="AdvPriestM1_WPN"), Items[1]=(Item="AdvPriestM1_PsiAmp"), Items[2]=(Item="HazmatVest"))
+Loadouts=(LoadoutName="AdvPriestM2_Loadout_BL", Items[0]=(Item="AdvPriestM2_WPN"), Items[1]=(Item="AdvPriestM2_PsiAmp"), Items[2]=(Item="HazmatVest"))
+Loadouts=(LoadoutName="AdvPriestM3_Loadout_BL", Items[0]=(Item="AdvPriestM3_WPN"), Items[1]=(Item="AdvPriestM3_PsiAmp"), Items[2]=(Item="HazmatVest"))

+Loadouts=(LoadoutName="AdvCommando_Loadout_BL", Items[0]=(Item="AdvCommando_WPN"), Items[1]=(Item="BioNanoScaleVest"))
+Loadouts=(LoadoutName="AdvScout_Loadout_BL", Items[0]=(Item="AdvScout_WPN"), Items[1]=(Item="BioNanoScaleVest"))
 
[XComGame.X2StrategyGameRulesetDataStructures]

HealSoldierProject_TimeScalar[0]=1.4 ;Easy
HealSoldierProject_TimeScalar[1]=1.4 ;Normal
HealSoldierProject_TimeScalar[2]=1.4 ;Classic
HealSoldierProject_TimeScalar[3]=1.4 ;Impossible
