[XComGame.X2Item_DefaultWeapons]

; These were a bit too evil

;AdvStunLancerM1_StunLance_BaseDamage=		(Damage=5, Spread = 1, PlusOne = 50,		Crit = 2, Pierce = 0, Shred=0, Tag = "", DamageType="Melee")
;AdvStunLancerM2_StunLance_BaseDamage=		(Damage=8, Spread = 1, PlusOne = 50,	Crit = 2, Pierce = 0, Shred=0, Tag = "", DamageType="Melee")
;AdvStunLancerM3_StunLance_BaseDamage=		(Damage=10, Spread = 2, PlusOne = 0,		Crit = 4, Pierce = 0, Shred=0, Tag = "", DamageType="Melee")
