
[XComGame.X2AIBTBehaviorTree]

+EquivalentAbilities=( KeyName=StandardShot, EquivalentAbilityName[0]=SnapShot)

+EquivalentAbilities=( KeyName=Suppression, EquivalentAbilityName[0]=M31_SuppressingFire)

-Behaviors=(BehaviorName=AshTryClumsyRand_10, NodeType=RandFilter, Child[0]=AshTryClumsy, Param[0]=10)  ;Param[0] gives a 10% chance

; Lets bump this up a bit, for content
+Behaviors=(BehaviorName=AshTryClumsyRand_10, NodeType=RandFilter, Child[0]=AshTryClumsy, Param[0]=50)  ;Param[0] gives a 50% chance now

+EquivalentAbilities=( KeyName=StandardMelee, EquivalentAbilityName[0]=DevastatingPunchMP)

+EquivalentAbilities=( KeyName=DevastatingPunch, EquivalentAbilityName[0]=DevastatingPunchMP)

[LW_Overhaul.UIScreenListener_Shell]

+BehaviorRemovals="BioViperRedFirstActionSelector"

+NewBehaviors=(BehaviorName=BioViperRedFirstActionSelector, NodeType=Selector, \\
    Child[0]=TryMeristViperBite, \\
    Child[1]=TryBind, \\
    Child[2]=TryMoveThenPoisonSpit, \\
    Child[3]=TryMoveThenPoisonSpitSingle, \\
    Child[4]=SelectMoveStandard, \\
    Child[5]=TryShootOrReloadOrOverwatch, \\
    Child[6]=HuntEnemyWithCover)