[XComGame.X2Character_DefaultCharacters]

; More mobility for Purifiers
[AdvPurifierM1 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=17

[AdvPurifierM1_Diff_0 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=17

[AdvPurifierM1_Diff_2 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=17

[AdvPurifierM1_Diff_3 X2CharacterTemplate]
CharacterBaseStats[eStat_ArmorMitigation]=3
CharacterBaseStats[eStat_HP]=7
CharacterBaseStats[eStat_Mobility]=17

[AdvPurifierM2 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=17

[AdvPurifierM2_Diff_0 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=17

[AdvPurifierM2_Diff_2 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=17

[AdvPurifierM2_Diff_3 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=17
CharacterBaseStats[eStat_ArmorMitigation]=4

[AdvPurifierM3 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=17

[AdvPurifierM3_Diff_0 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=17

[AdvPurifierM3_Diff_2 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=17

[AdvPurifierM3_Diff_3 X2CharacterTemplate]
CharacterBaseStats[eStat_ArmorMitigation]=6
CharacterBaseStats[eStat_Mobility]=17

; More mobility for Najas so they can flank/snapshot
[NajaM1 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=18

[NajaM2 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=18

[NajaM3 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=20

[NajaM3_Diff_1 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=20

[NajaM3_Diff_2 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=20

[NajaM3_Diff_3 X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=20

; More mobility for Bio Vipers so they can bite
[BioViperSilver X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=16

[BioViperGold X2CharacterTemplate]
CharacterBaseStats[eStat_Mobility]=18

[AdvTrooperM1 X2CharacterTemplate]
CharacterBaseStats[eStat_ArmorMitigation]=1

[AdvTrooperM2 X2CharacterTemplate]
CharacterBaseStats[eStat_ArmorMitigation]=1

[AdvTrooperM3 X2CharacterTemplate]
CharacterBaseStats[eStat_ArmorMitigation]=1


[LWDroneM1 X2CharacterTemplate]

[LWDroneM1_Diff_3 X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5
CharacterBaseStats[eStat_Defense]=10

[LWDroneM2_Diff_3 X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=13
CharacterBaseStats[eStat_Defense]=25


; XCOM BUFFS!

[Soldier X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5

[Soldier_Diff_1 X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5

[Soldier_Diff_2 X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5

[Soldier_Diff_3 X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5


[ReaperSoldier X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5

[ReaperSoldier_Diff_1 X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5


[ReaperSoldier_Diff_2 X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5


[ReaperSoldier_Diff_3 X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5


[SkirmisherSoldier X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5


[SkirmisherSoldier_Diff_0 X2CharacterTemplate]
CharacterBaseStats[eStat_HP] = 6

[SkirmisherSoldier_Diff_1 X2CharacterTemplate]
CharacterBaseStats[eStat_HP] =5

[SkirmisherSoldier_Diff_2 X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5

[SkirmisherSoldier_Diff_3 X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5

[TemplarSoldier X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=6

[TemplarSoldier_Diff_0 X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5

[TemplarSoldier_Diff_1 X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5

[TemplarSoldier_Diff_2 X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5

[TemplarSoldier_Diff_3 X2CharacterTemplate]
CharacterBaseStats[eStat_HP]=5